### ISSUE TITLE
How to contact users via mail glyphicon 

### ISSUE THREAD

**Issue by ejolly** [HarvardEconCS/turkserver-meteor#47]
Is there something additional required to setup this functionality or should it simply work based on the AWS key info in the settings file? Workers don't seem to be receiving messages sent using the turkserver admin interface.

**Comment by mizzao** [comment]
No, it should just work. Can you make sure that (1) you are on the latest commit (`git checkout master; git pull; git submodule update --recursive`) and (2) that the worker you are trying to e-mail has worked for you before?

If you are not on the latest commit, you might not be seeing errors thrown when you try to e-mail workers, which would show up via a modal as soon as you hit the button.

**Comment by ejolly** [comment]
I actually ran a very small batch live and had an issue where user A disconnected (and never reconnected) while two users were in an experiment together, thereby preventing user B from advancing and completing the HIT (obviously a bug I need to fix). I was trying to message the user still connected to let them know I was going to end the experiment instance so they could submit the HIT and still get paid, but they didn't seem to receive my message through the admin interfaced and instead contacted me separately themselves. 

So is it not possible to message a user while they are in your experiment for the first time?

**Comment by mizzao** [comment]
No, it isn't unfortunately. That is why I typically put up low-dollar-amount recruiting HITs for all of my experiments, so that (1) the user is reachable, (2) we can explain the instructions separately from trying to match users, and (3) we know that their browser works with Meteor. (Surprisingly the latter is still not true for some people).

It is important to consider all variations of attrition, disconnection, and dropping out in your experiment design so that you know that both the operation of the experiment and your data collection are robust to it.

Also, always test what you can either using automated tests or in the sandbox versus live tests. Pay attention to your TurkOpticon reviews, and always provide good service if you want to be able to recruit people to do weird stuff in the future. Let me know if I can help further!

**Comment by ejolly** [comment]
Ah I see. Definitely trying to provide good service and staying on top of the TurkOpticon reviews. Thanks for the advice!
